### ISSUE TITLE
Web is not working on iOS and Safari browser on MacOS

### ISSUE THREAD

**Issue by samuel-bily** [DCsunset/taskwarrior-webui#50] opened 2022-10-16 21:24 UTC
Firefox and chrome work great on macos, safari leads to infinite circular progress bar with this stacktrace in console:

**Stacktrace from JS console:**
`[Error] SyntaxError: Invalid regular expression: invalid group specifier name
	(anonymná funkcia) (cf3ecde.js:2)

[Error] ChunkLoadError: Loading chunk 2 failed.
(missing: http://myfancysite.com/_nuxt/cf3ecde.js)
(anonymná funkcia) — 791115c.js:1:1032
component — d16ff64.js:2:82611
v — ac36df6.js:2:83487
(anonymná funkcia) — ac36df6.js:2:83272
r — ac36df6.js:2:72904
l — ac36df6.js:2:73108
(anonymná funkcia) — ac36df6.js:2:73167
Promise
(anonymná funkcia) — ac36df6.js:2:73058
(anonymná funkcia) — d16ff64.js:2:13199
reduce
map
O — d16ff64.js:2:13097
B — d16ff64.js:2:13310
v — ac36df6.js:2:83487
(anonymná funkcia) — ac36df6.js:2:83272
r — ac36df6.js:2:72904
l — ac36df6.js:2:73108
(anonymná funkcia) — ac36df6.js:2:73167
Promise
(anonymná funkcia) — ac36df6.js:2:73058
(anonymná funkcia) — d16ff64.js:2:15521
v — ac36df6.js:2:83487
(anonymná funkcia) — ac36df6.js:2:83272
r — ac36df6.js:2:72904
l — ac36df6.js:2:73108
(anonymná funkcia) — ac36df6.js:2:73167
Promise
(anonymná funkcia) — ac36df6.js:2:73058
v — ac36df6.js:2:83487
(anonymná funkcia) — ac36df6.js:2:83272
r — ac36df6.js:2:72904
l — ac36df6.js:2:73108
promiseReactionJob
promiseReactionJob`

**Screenshot from iOS safari or PWA:**
![IMG_2820](https://user-images.githubusercontent.com/17648623/196058731-9ce753b3-29a5-4be7-84f0-1d9b91bdbc40.jpg)

**Screenshot from Safari MacOS**
<img width="1323" alt="Snímka obrazovky 2022-10-16 o 23 24 18" src="https://user-images.githubusercontent.com/17648623/196059029-616db166-b45d-449c-965e-e7821af03b02.png">

**Comment by JoshMock** [comment] 2022-10-16 23:27
Duplicate of https://github.com/DCsunset/taskwarrior-webui/issues/21, which has more context. I’m debugging this as I have time.

**Comment by DCsunset** [comment] 2022-10-17 20:15
This should be fixed now. See #21.

**Closed by DCsunset** 2022-10-17 20:15 UTC
