### ISSUE TITLE
Cannot run taskwarrior-webui. Perhaps simply missing docu?

### ISSUE THREAD

**Issue by mads-bisgaard** [DCsunset/taskwarrior-webui#55] opened 2022-11-03 22:18 UTC
Hi, I would like to use taskwarrior-webui. However, when I run
```
sudo docker run -p 8080:80 --name taskwarrior-webui  -v $HOME/.taskrc:/.taskrc -v $HOME/.task:/.task  dcsunset/taskwarrior-webui
```
all I see is 
```
> backend@1.0.0 start
> node ./dist/app.js

Server listening on http://0.0.0.0:3000
```
From the README it seems that this should be sufficient to run `taskwarrior-webui`. Am I missing something?
Thanks in advance :)

**Comment by super-ben** [comment] 2022-11-06 18:57
Do you run the command above as root? If so, the problem is that $HOME will be the root's home (/root). Either run it as your user or map the volume accordingly.

**Comment by Constantin1489** [comment] 2023-07-07 18:13
I agree with @super-ben. 

For docker,
```
TWDIR=<write your absolute path of them>
# If your tw db is in default path, use the result of `echo $HOME`.

sudo docker run -p 8080:80 --name taskwarrior-webui  -v $HOME/.taskrc:/.taskrc -v $HOME/.task:/.task  dcsunset/taskwarrior-webui
```

But if you use podman, try `:z` or `:Z` labels. See the detail [here](https://unix.stackexchange.com/questions/651198/podman-volume-mounts-when-to-use-the-z-or-z-suffix).

For podman,

```
sudo podman run -p 8080:80 --name taskwarrior-webui  -v $HOME/.taskrc:/.taskrc:z -v $HOME/.task:/.task:z  dcsunset/taskwarrior-webui
```

**Comment by mads-bisgaard** [comment] 2023-07-10 21:44
> I agree with @super-ben.
> 
> For docker,
> 
> ```
> # If your tw db is in a default path, use the result of `echo $HOME`.
> TWDIR=<write your absolute path of them>
> sudo docker run -p 8080:80 --name taskwarrior-webui  -v $TWDIR/.taskrc:/.taskrc -v $TWDIR/.task:/.task  dcsunset/taskwarrior-webui
> ```
> 
> But if you use podman, try `:z` or `:Z` labels. See the detail [here](https://unix.stackexchange.com/questions/651198/podman-volume-mounts-when-to-use-the-z-or-z-suffix).
> 
> For podman,
> 
> ```
> # without sudo
> podman run -p 8080:80 --name taskwarrior-webui  -v $HOME/.taskrc:/.taskrc:z -v $HOME/.task:/.task:z  dcsunset/taskwarrior-webui
> ```

Thanks a lot @Constantin1489. This works in the sense, that I see
```

> backend@1.0.0 start
> node ./dist/app.js

Server listening on http://0.0.0.0:3000
```
However, I still see 
![image](https://github.com/DCsunset/taskwarrior-webui/assets/63423058/d106a466-a408-41cd-9db0-78413d537d44)

Could it be there is some network issue when I am running the docker container as root?

**Comment by super-ben** [comment] 2023-07-10 21:55
I would recommend adding your user to the docker group and running it from your home, so your mapping will be correct. If you wish, I can show you my “production” docker compose file.

**Comment by mads-bisgaard** [comment] 2023-07-10 21:56
> I would recommend adding your user to the docker group and running it from your home, so your mapping will be correct. If you wish, I can show you my “production” docker compose file.

Thanks I will try it out

**Comment by Constantin1489** [comment] 2023-07-10 22:42
@mads-bisgaard Because you set your port as 8080, then your URL is `http://0.0.0.0:8080`.

**Comment by Taomach** [comment] 2024-09-24 14:08
I have similar problem. I've tried what @Constantin1489 recommended, and start docker from my user with this command:
`docker run -p 8080:80 --name taskwarrior-webui -e TASKRC=$HOME/.taskrc -e TASKDATA=$HOME/.task -v $HOME/.taskrc:/.taskrc:z -v $HOME/.task:/.task:z dcsunset/taskwarrior-webui:3`
The app runs, but my existing task data isn't shown, and I have this error in the docker console:
`Could not write to '/home/$MYUSER/.taskrc'`
Although if I login inside the docker shell, the file is writeable. How do I resolve this?

**Comment by DCsunset** [comment] 2024-09-25 18:44
@Taomach You have set the environment variable to `$HOME/.task` but you are not mounting it to `/.task`. Please follow the README to run the command. (Remove the env or change the mount point)

**Comment by Taomach** [comment] 2024-09-26 08:10
> @Taomach You set the environment variable to `$HOME/.task` but you mounted it to `/.task`. Please follow the README to run the command. (Remove the env or change the mount point)

Okay, I misunderstood the meaning of the env commands, I added them because without them I has the same problem, but also this error:
`Could not read include file '/root/.task/my-colors.theme'`
because of the custom theme definiton in my `.taskrc`. It seems that without the env commands my `.taskrc` is used, but there are still no tasks shown in the web interface.

**Comment by DCsunset** [comment] 2024-09-26 12:26
@Taomach  This scenario is mentioned in the README already. Did you try the command in https://github.com/DCsunset/taskwarrior-webui#deployment? That was what I meant by "change the mount point".

**Comment by Taomach** [comment] 2024-09-26 12:51
@DCsunset I tried again to reproduce the problem, and, mysteriously, everything worked this time. No idea what I did differently, but oh well.)
Thank you!

**Comment by DCsunset** [comment] 2024-09-26 12:52
It's just because you modified the command. It should have been `-v $HOME/.task:$HOME/.task`.

Closing this issue as completed.

**Closed by DCsunset** 2024-09-26 12:52 UTC
